
name: Greeting on a variable day

on: push

env:
  DAY_OF_WEEK: Monday ## Environment variable for the entire workflow

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello ## Environment variable for the job
    steps:
      - name: "Say Hello Henrieke it's Monday"
        run: echo "$Greeting $MY_NAME. Today is $DAY_OF_WEEK!"
        env:
          DataScientest_Test_Environment: ${{ secrets.MY_NAME }}
